### ISSUE TITLE
License information

### ISSUE THREAD

**Issue by szhem** [gridkit/jvm-attach#2]
Hi there,

It seems that this lib does not include any license information, although it is shipped as a dependency with [Apache 2](https://github.com/aragozin/jvm-tools/blob/master/LICENSE) licensed [jvm-tools](https://github.com/aragozin/jvm-tools).

Could you please shed some light on the actual license of this library?

**Comment by aragozin** [comment]
pom.xml contains license section (which is Apache 2). 
I've added LICENSE.txt to make it more clear.

**Comment by szhem** [comment]
Great! Thanks a lot!
