### ISSUE TITLE
Support custom tools.jar location

### ISSUE THREAD

**Issue by cykl** [gridkit/jvm-attach#3]
Hi,

`jvm-attach` currently relies on a JDK being deployed as the `/../lib/tools.jar` is hard coded. Unfortunately, some organizations deploy JREs which hinder troubleshooting as many tools are not available.

My workaround is to extract `tools.jar` and `libattach.so` from the matching JDK and upload them on the server. This is lightweight, ~18MB + ~16KB,  and almost safe.  Setting `LD_LIBRARY_PATH` is easy, but the hard coded `/../lib/tools.jar` force me to store `tools.jar` in an uncomfortable path.  I would prefer to upload all that transient stuff into a safer place.

Would it make sense to add a system property to set a custom path for `tools.jar`?

**Comment by aragozin** [comment]
You can add tools.jar to normal Java classpath (e.g. `-cp $CLASSPATH:tools.jar`) . If tools.jar is not found library tries to load classes anyway and complain only if classes from tools.jar cannot be loaded.

**Comment by cykl** [comment]
Of course! Thanks for stating the obvious.
